# Generated by Django 5.1.6 on 2025-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('ficcion', 'Ficción'), ('historia', 'Historia'), ('no_ficcion', 'No ficción'), ('fantasia', 'Fantasía'), ('ciencia', 'Ciencia'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
